#!/usr/bin/env python3
"""
Fix ValuScan token refresher on VPS.

This script:
1. Creates/updates credentials file
2. Configures the CDP-based token refresher
3. Tests the login
4. Restarts the service

Run on VPS:
  python fix_token_refresher_vps.py
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

# Configuration
SIGNAL_MONITOR_DIR = Path("/root/valuescan/signal_monitor")
CREDENTIALS_FILE = SIGNAL_MONITOR_DIR / "valuescan_credentials.json"
LOCALSTORAGE_FILE = SIGNAL_MONITOR_DIR / "valuescan_localstorage.json"
ENV_FILE = Path("/root/valuescan/config/valuescan.env")

# Credentials from env or fallback
EMAIL = os.getenv("VALUESCAN_EMAIL", "ymy_live@outlook.com")
PASSWORD = os.getenv("VALUESCAN_PASSWORD", "Qq159741.")


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}")


def save_credentials():
    """Save credentials to file."""
    log(f"Saving credentials to {CREDENTIALS_FILE}")
    SIGNAL_MONITOR_DIR.mkdir(parents=True, exist_ok=True)
    
    creds = {"email": EMAIL, "password": PASSWORD}
    tmp = CREDENTIALS_FILE.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(creds, indent=2), encoding="utf-8")
    os.replace(tmp, CREDENTIALS_FILE)
    os.chmod(CREDENTIALS_FILE, 0o600)
    log("Credentials saved")


def update_env_file():
    """Ensure env file has correct settings."""
    log(f"Updating {ENV_FILE}")
    
    env_content = f"""# Generated by fix_token_refresher_vps.py
VALUESCAN_LOGIN_METHOD=cdp
VALUESCAN_REFRESH_URL=https://api.valuescan.io/api/account/refreshToken
VALUESCAN_AUTO_RELOGIN=1
VALUESCAN_AUTO_RELOGIN_USE_BROWSER=1
VALUESCAN_AUTO_RELOGIN_COOLDOWN=300
VALUESCAN_PASSWORD={PASSWORD}
VALUESCAN_EMAIL={EMAIL}
VALUESCAN_CDP_PORT=9222
VALUESCAN_BROWSER_STARTUP_TIMEOUT=60
SOCKS5_PROXY=socks5://127.0.0.1:1080
"""
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text(env_content, encoding="utf-8")
    log("Env file updated")


def kill_stale_browsers():
    """Kill stale browser processes."""
    log("Killing stale browser processes...")
    for proc in ["chromium", "chrome", "chromium-browser"]:
        try:
            subprocess.run(["pkill", "-9", proc], capture_output=True, timeout=5)
        except Exception:
            pass
    time.sleep(2)


def test_cdp_login():
    """Test CDP login."""
    log("Testing CDP login...")
    
    script = SIGNAL_MONITOR_DIR / "cdp_token_refresher.py"
    if not script.exists():
        log(f"ERROR: CDP script not found: {script}")
        return False
    
    env = os.environ.copy()
    env["VALUESCAN_EMAIL"] = EMAIL
    env["VALUESCAN_PASSWORD"] = PASSWORD
    env["VALUESCAN_TOKEN_FILE"] = str(LOCALSTORAGE_FILE)
    env["DISPLAY"] = ":99"
    
    try:
        result = subprocess.run(
            [sys.executable, str(script), "--once", "--force"],
            cwd=str(SIGNAL_MONITOR_DIR),
            env=env,
            capture_output=True,
            text=True,
            timeout=180
        )
        log(f"Exit code: {result.returncode}")
        if result.stdout:
            for line in result.stdout.strip().split("\n")[-10:]:
                log(f"  {line}")
        if result.stderr:
            for line in result.stderr.strip().split("\n")[-5:]:
                log(f"  [stderr] {line}")
        return result.returncode == 0
    except subprocess.TimeoutExpired:
        log("ERROR: Login timed out after 180 seconds")
        return False
    except Exception as exc:
        log(f"ERROR: {exc}")
        return False


def check_token():
    """Check if token is valid."""
    if not LOCALSTORAGE_FILE.exists():
        log("Token file does not exist")
        return False
    
    try:
        data = json.loads(LOCALSTORAGE_FILE.read_text(encoding="utf-8"))
        token = data.get("account_token", "")
        if not token:
            log("No account_token in file")
            return False
        
        # Decode JWT to check expiry
        import base64
        parts = token.split(".")
        if len(parts) < 2:
            log("Invalid token format")
            return False
        
        payload = parts[1] + "=" * (-len(parts[1]) % 4)
        decoded = json.loads(base64.urlsafe_b64decode(payload))
        exp = decoded.get("exp", 0)
        now = int(time.time())
        remaining = exp - now
        
        if remaining > 0:
            log(f"Token valid for {remaining // 60} minutes ({remaining // 3600:.1f} hours)")
            return True
        else:
            log(f"Token expired {-remaining} seconds ago")
            return False
    except Exception as exc:
        log(f"Error checking token: {exc}")
        return False


def restart_services():
    """Restart related services."""
    log("Restarting services...")
    services = [
        "valuescan-signal",
        "valuescan-token-refresher",
    ]
    for svc in services:
        try:
            subprocess.run(["systemctl", "restart", svc], capture_output=True, timeout=30)
            log(f"  Restarted {svc}")
        except Exception as exc:
            log(f"  Failed to restart {svc}: {exc}")


def main():
    log("=" * 50)
    log("ValuScan Token Refresher Fix")
    log("=" * 50)
    
    # Step 1: Save credentials
    save_credentials()
    
    # Step 2: Update env file
    update_env_file()
    
    # Step 3: Kill stale browsers
    kill_stale_browsers()
    
    # Step 4: Check current token
    if check_token():
        log("Token is currently valid")
    else:
        log("Token needs refresh")
    
    # Step 5: Test CDP login
    success = test_cdp_login()
    
    if success:
        log("CDP login successful!")
        check_token()
    else:
        log("CDP login failed")
        log("Checking if token was obtained despite error...")
        if check_token():
            log("Token appears valid despite error")
            success = True
    
    # Step 6: Restart services
    if success:
        restart_services()
        log("=" * 50)
        log("Fix complete! Token refresher should now work.")
        log("=" * 50)
        return 0
    else:
        log("=" * 50)
        log("Fix incomplete - manual intervention may be needed")
        log("Try running: python /root/valuescan/signal_monitor/cdp_token_refresher.py --once --force")
        log("=" * 50)
        return 1


if __name__ == "__main__":
    sys.exit(main())
